EmpManager/Controllers/EmployeesController.cs
using EmpManager.Data;
using EmpManager.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EmpManager.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly AppDbContext _context;

        public EmployeesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employees.ToListAsync());
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                TempData["error"] = "Employee not found";
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Firstname,Lastname,Email,Phonenumber")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                TempData["success"] = "Employee added successfully";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "Something went wrong";
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                TempData["error"] = "Employee not found";
                return NotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Firstname,Lastname,Email,Phonenumber")] Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["success"] = "Employee updated";
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                TempData["error"] = "Employee not found";
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await _context.Employees.FindAsync(id);
            if (employee != null)
            {
                _context.Employees.Remove(employee);
            }

            await _context.SaveChangesAsync();
            TempData["success"] = "Employee Deleted";
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.Id == id);
        }
    }
}

EmpManager/Controllers/LeavesController.cs
using EmpManager.Data;
using EmpManager.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EmpManager.Controllers
{
    public class LeavesController : Controller
    {
        private readonly AppDbContext _context;

        public LeavesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Leaves
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Leaves.Include(l => l.Employee);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Leaves/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leave = await _context.Leaves
                .Include(l => l.Employee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leave == null)
            {
                TempData["error"] = "Application not found";
                return NotFound();
            }

            return View(leave);
        }

        // GET: Leaves/Create
        public IActionResult Create()
        {
            ViewData["FkEmployeeId"] = new SelectList(_context.Employees, "Id", "Fullname");
            return View();
        }

        // POST: Leaves/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Type,StartDate,EndDate,FkEmployeeId")] Leave leave)
        {
            if (ModelState.IsValid)
            {
                _context.Add(leave);
                await _context.SaveChangesAsync();
                TempData["success"] = "Application created successfully";
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkEmployeeId"] = new SelectList(_context.Employees, "Id", "Fullname", leave.FkEmployeeId);
            return View(leave);
        }

        // GET: Leaves/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leave = await _context.Leaves.FindAsync(id);
            if (leave == null)
            {
                TempData["error"] = "Application not found";
                return NotFound();
            }
            ViewData["FkEmployeeId"] = new SelectList(_context.Employees, "Id", "Fullname", leave.FkEmployeeId);
            return View(leave);
        }

        // POST: Leaves/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Type,StartDate,EndDate, Handled, IsApproved, FkEmployeeId")] Leave leave)
        {
            if (id != leave.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(leave);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeaveExists(leave.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["success"] = "Application updated";
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkEmployeeId"] = new SelectList(_context.Employees, "Id", "Fullname", leave.FkEmployeeId);
            return View(leave);
        }

        // GET: Leaves/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leave = await _context.Leaves
                .Include(l => l.Employee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leave == null)
            {
                TempData["error"] = "Application not found";
                return NotFound();
            }

            return View(leave);
        }

        // POST: Leaves/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var leave = await _context.Leaves.FindAsync(id);
            if (leave != null)
            {
                _context.Leaves.Remove(leave);
            }

            await _context.SaveChangesAsync();
            TempData["success"] = "Application deleted";
            return RedirectToAction(nameof(Index));
        }

        private bool LeaveExists(int id)
        {
            return _context.Leaves.Any(e => e.Id == id);
        }


        public async Task<IActionResult> ViewApplication()
        {
            var leaves = await _context.Leaves.Include(l => l.Employee).ToListAsync();
            if (leaves.Count == 0)
            {
                TempData["error"] = "No Data was found";
                return View();
            }
            return View(leaves);
        }

        public async Task<IActionResult> Approve(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var leave = await _context.Leaves.FirstOrDefaultAsync(x => x.Id == id);
            if (leave == null)
            {
                return NotFound();
            }
            leave.IsApproved = true;
            leave.Handled = true;

            _context.Leaves.Update(leave);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Deny(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var leave = await _context.Leaves.FirstOrDefaultAsync(x => x.Id == id);
            if (leave == null)
            {
                return NotFound();
            }

            leave.Handled = true;

            _context.Leaves.Update(leave);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

EmpManager/Controllers/StatisticsController.cs
using EmpManager.Data;
using EmpManager.Models;
using EmpManager.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EmpManager.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly AppDbContext _context;

        public StatisticsController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SearchByName()
        {
            ViewData["FkEmployeeId"] = new SelectList(_context.Employees, "Id", "Fullname");
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> SearchByName(int id)
        {
            if (id != 0)
            {
                var employee = await _context.Employees
               .Include(e => e.LeaveHistory)
               .FirstOrDefaultAsync(x => x.Id == id);

                if (employee == null)
                {
                    TempData["error"] = "Could not find Employee";
                    return RedirectToAction("Index");
                }
                if (employee.LeaveHistory.Count == 0)
                {
                    TempData["error"] = "Employee have no history";
                    return RedirectToAction(nameof(Index));
                }

                return View("SearchResultFromNameSearch", employee);
            }

            TempData["error"] = "Something went wrong";
            return View();
        }


        public IActionResult SearchByDate()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> SearchByDate(DateTime searchDate)
        {
            if (ModelState.IsValid)
            {
                var userinput = searchDate.Month;

                //only get employees who has Leave created in searchDate
                List<Employee> employee = await _context.Employees
                    .Where(e => e.LeaveHistory.Any(l => l.Created.Month == userinput))
                    .Include(e => e.LeaveHistory.Where(l => l.Created.Month == userinput)).ToListAsync();

                if (employee.Count == 0)
                {
                    TempData["error"] = "No employee found in search";
                    return View();
                }
                var model = new SearchResultVM()
                {
                    SearchDate = searchDate,
                    Employees = employee
                };
                return View("SearchResult", model);
            }
            return View(searchDate);
        }

    }
}

EmpManager/Views/Shared/NotFound.cshtml
<div class="container">
    <h3 class="text-center text-info my-3">You have reached the end of internet!!</h3>
    <div class="text-center">
        <img src="/images/404NotFound.png" alt="Error" style="width: 800px" />
    </div>
    <div class="p-3 text-center">
        <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Home</a>
    </div>
</div>

EmpManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmpManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmpManager.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black ">
            <div class="container-fluid">
                <a class="navbar-brand text-info" asp-area="" asp-controller="Home" asp-action="Index">EmpManager</a>
                <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Leaves" asp-action="Index">Leaves</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Leaves" asp-action="ViewApplication">View Applications</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Statistics" asp-action="Index">Statistics</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="pb-3">
        <partial name="_Notification" />
        @RenderBody()
    </main>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EmpManager - Labb1
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EmpManager/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
      toastr.error('@TempData["error"]')
    </script>
}